// APARTMENTS
export const RESET_SEARCH_FILTER_DEFAULT = 'RESET_SEARCH_FILTER_DEFAULT'
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS'
export const SET_LIST_LOCALITY = 'SET_LIST_LOCALITY'
export const SET_LIST_FILTERS = 'SET_LIST_FILTERS'
export const SET_APARTMENT = 'SET_APARTMENT'
export const SET_APARTMENTS_LIST = 'SET_APARTMENTS_LIST'
export const AP_APARTMENTS_LOADING = 'AP_APARTMENTS_LOADING'
export const AP_APARTMENTS_ERROR = 'AP_APARTMENTS_ERROR'

// LOCATIONS
export const SET_LOCATION = 'SET_LOCATION'
export const SET_LOCATIONS_LIST = 'SET_LOCATIONS_LIST'
export const AP_LOCATIONS_LOADING = 'AP_LOCATIONS_LOADING'
export const AP_LOCATIONS_ERROR = 'AP_LOCATIONS_ERROR'